# spring boot management server instance properties
management:
  server:
    port: 8080
  endpoints: 
    web: 
      exposure: 
        include: '*'
     
server:
  port: 8080
     
spring:
  info:
    app:
      name: credable-interview
      description: This service will orchastrate traffic between LMS, CBS and Mobile Banking and other channels
      version: 1.0.0
      engineName: credable-interview
  activemq:
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 200
      idle-timeout: 30
      max-sessions-per-connection: 500
      block-if-full: false
      time-between-expiration-check: 100
    #broker-url: tcp://localhost:61616
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    loansRequestQueue: LOANS-QUEUE
    scoreRequestQueue: SCORE-REQUESTS-QUEUE
    maxRetries: 5
  jackson:
    default-property-inclusion: non_null

  data:
    mongodb:
      uri: mongodb+srv://credable:credable2025@credable.huset.mongodb.net/?retryWrites=true&w=majority&appName=credable
      database: credable

  application:
    name: credable-interview
  #profiles: dev
  config: 
    activate:
      on-profile: dev



scoring:
  service:
    baseurl : https://credable.free.beeceptor.com/
    create-client: createClient
    url: http://102.220.169.7
    name: "Okiri George cradable"
    username: "george"
    password: "george123"

cbs:
  auth:
    username: admin
    password: pwd123



